### ISSUE TITLE
HOME - Ticker title: Clipped text visible using chrome.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/The-Cancer-Centre#25] opened 2016-04-06 06:41 UTC
![24](https://cloud.githubusercontent.com/assets/18256652/14307983/98619ce4-fc05-11e5-861a-c3ef34caea26.png)

**Comment by euveng** [comment] 2016-04-13 05:39
The ticker is built to truncate the content after 160 characters. It's not a bug - just a content issue, so won't fix.

**Closed** 2016-04-13 09:05 UTC
Labels: bug, fixed
